GET http://localhost:3000/products

###
POST http://localhost:3000/products
Content-Type: application/json

{   
    "name": "Produtinho 90",
    "description": "Produtinho",
    "image_url": "https://via.placeholder.com/150",
    "price": 90
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "username": "chris",
    "password": "chris"
}

###
GET http://localhost:3000/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInVzZXJuYW1lIjoiY2hyaXMiLCJpYXQiOjE3MDY5ODI3NzQsImV4cCI6MTcwNzA2OTE3NH0.RvJD1jAKgeTD7g3zy3swe854Jy2xZdWOBUNl__bO7WA

###
GET http://localhost:3000/orders/cf89b8c7-fcf1-4f62-b05a-3dbfd0f6f006
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInVzZXJuYW1lIjoiY2hyaXMiLCJpYXQiOjE3MDY5ODI3NzQsImV4cCI6MTcwNzA2OTE3NH0.RvJD1jAKgeTD7g3zy3swe854Jy2xZdWOBUNl__bO7WA

###
POST http://localhost:3000/orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInVzZXJuYW1lIjoiY2hyaXMiLCJpYXQiOjE3MDY5ODI3NzQsImV4cCI6MTcwNzA2OTE3NH0.RvJD1jAKgeTD7g3zy3swe854Jy2xZdWOBUNl__bO7WA

{   
    "items":[
        {
            "product_id": "cfe6c54e-6298-4787-82f1-8b188677da96",
            "quantity": 1
        }
    ],
    "card_hash": "123"
}

